version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tutoseu
      MYSQL_DATABASE: tutoseu
      MYSQL_USER: myuser
      MYSQL_PASSWORD: monpassword
    ports:
    - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: myuser
      PMA_PASSWORD: monpassword