version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: OGPT
      MYSQL_USER: OGPT
      MYSQL_PASSWORD: JadoreOGE
    ports:
    - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: OGPT
      PMA_PASSWORD: JadoreOGE